// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2KX27hIMQQ5K46ztag-dIEwP-eg9MF74',
    appId: '1:395917096520:web:ce77a3e6ba1ab2ff1dca7d',
    messagingSenderId: '395917096520',
    projectId: 'laundryeah',
    authDomain: 'laundryeah.firebaseapp.com',
    storageBucket: 'laundryeah.appspot.com',
    measurementId: 'G-RFEHCKK4KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGk-K257LDv7F8hzxWuXAG6WCzBHcpadc',
    appId: '1:395917096520:android:1555e13a90aedf561dca7d',
    messagingSenderId: '395917096520',
    projectId: 'laundryeah',
    storageBucket: 'laundryeah.appspot.com',
  );
}
